name: Run PHP Stalker Playlist

on:
  workflow_dispatch:  # manual trigger
  push:
    branches: [ main ]  # or change to your branch

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install PHP & Apache
      - name: Install PHP & Apache
        run: |
          sudo apt update
          sudo apt install -y apache2 php libapache2-mod-php php-curl php-mbstring php-xml php-json

      # Step 3: Move files to web server root
      - name: Set up Apache web root
        run: |
          sudo cp -r . /var/www/html/
          sudo chown -R www-data:www-data /var/www/html

      # Step 4: Start Apache (optional, if you want to test via curl localhost)
      - name: Start Apache
        run: sudo systemctl start apache2

      # Step 5: Run the PHP script
      - name: Execute playlist.php
        run: php playlist.php > playlist_output.m3u

      # Step 6: Upload the generated M3U file as an artifact
      - name: Upload Playlist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playlist-output
          path: playlist_output.m3u
